name: "CI"

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install pycodestyle yamllint

      - name: Yaml Lint Integration Code.
        run: yamllint tests/integration/aws
        
      - name: Pycodestyle Lint Module
        run: pycodestyle --config=.pycodestyle plugins/modules/

      - name: Pycodestyle Lint Module Utils
        run: pycodestyle --config=.pycodestyle plugins/module_utils/

      - name: Automatic Doc Creation Tool Installation
        run: pip3 install git+https://github.com/ansible-network/collection_prep.git

      - name: Run Automatic Doc Creation Tool
        run: collection_prep_add_docs -p . -b master

      - name: Try to build collection with ansible-galaxy
        run: ansible-galaxy collection build -v
