name: "Security"

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install bandit

      - name: Python Static Analysis (bandit)
        run: bandit -r -v plugins/
